### ISSUE TITLE
Dokumentacja

### ISSUE THREAD

**Issue by AdrianHarenczyk** [boczkas/XOTheGame#1]
https://github.com/boczkas/XOTheGame/blob/090dd2027096a64ad63111b1ccb3c581f926d0d6/src/main/java/com/przemyslawjakubowski/GameState.java#L6

Brakuje dokumentacji, co robi dany interface.

**Comment by boczkas** [comment]
Dokumentacja zostanie wykonana jak projekt troszkę dojrzeje
