### ISSUE TITLE
Podsumowanie

### ISSUE THREAD

**Issue by gacikjakub** [boczkas/XOTheGame#2]
Dobra robota. 
Ciekawy podział na interfejsy i klasy. 
Dobrze, że od początku używasz interfejsów funkcyjnych Supplier i Consumer. 
Brakuje dokumentacji. 
Trochę za mało testów

**Comment by boczkas** [comment]
Dzięki wielkie :)
Testy planuję mieć tylko do publicznych interfejsów klas
