### ISSUE TITLE
Sprawdzanie poprawności koordynat względem tablicy powinno przyjmować gotowe koordynaty, a nie Stringa

### ISSUE THREAD

**Issue by totine** [boczkas/XOTheGame#21]
https://github.com/boczkas/XOTheGame/blob/71e41374d9c683a79ba4087c4617a7827d0def1b/src/main/java/com/przemyslawjakubowski/Board.java#L60

wcześniejszy matcher załatwia sprawę sprawdzenia literek, więc nie trzeba ponownie sprawdzać

**Comment by boczkas** [comment]
Zrobione
