### ISSUE TITLE
Dokumentacja cd.

### ISSUE THREAD

**Issue by AdrianHarenczyk** [boczkas/XOTheGame#3]
https://github.com/boczkas/XOTheGame/blob/090dd2027096a64ad63111b1ccb3c581f926d0d6/src/main/java/com/przemyslawjakubowski/Player.java#L3

brakuje informacji o danej klasie, co konkretnie robi.

**Comment by LIttleAncientForestKami** [comment]
Plus 1, aczkolwiek można zrobić to później, bo to wczesny etap. Ja np. nie będę teraz nikomu nic pisał o dokumentacji. Później, tak, ale nie teraz.

**Comment by boczkas** [comment]
Dokumentacja zostanie wykonana jak projekt troszkę dojrzeje.
