### ISSUE TITLE
Mantra w sumie

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [boczkas/XOTheGame#9]
Przemko_OX/: -2 za kwity/howToRun.json Migawek 2 boczkas/XOTheGame +1 za .gitignore -1 za kwity/gitattr.json -1 za kwity/gitmailmap.json -1 za kwity/UTF8missing.json, +5 za Mavena, +5 za kompilację i testy

**Comment by boczkas** [comment]
Dziękować
